In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [14]:
#Print the type
b = np.array([[1,3,5,7],[8,6,6,4]])
type(b)

numpy.ndarray

In [53]:
#Repeat numbers
c = np.array([1,2,3])
c1=np.repeat(c,6,axis=0)
c1

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3])

In [71]:
q = np.array([[1,2,3],[4,5,6]])
q

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
## Statistics

In [79]:
#Adding two diffrent array
r = np.sum(q, axis = 0)
r

array([5, 7, 9])

In [80]:
#Maximum & Minimum numbers
q = np.min([[1,2,3],[4,5,6]])
q = np.max([[1,2,3],[4,5,6]])
q

1

In [84]:
#Mathematics
q = np.array([1,2,3])
q+1
q-1
q%1
q*1
q/1

array([1., 2., 3.])

In [86]:
#Random Decimal Number
p = np.random.rand(2,3)  #randint use for Random integer value.
p

array([[0.59440533, 0.29948794, 0.8726726 ],
       [0.70274043, 0.99382193, 0.84412219]])

In [88]:
#All one's Matrix
w = np.ones((4,2,3), dtype= 'int32')
w

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [89]:
#Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])